name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'  # Specify the required Python version

      - name: Install dependencies
        run: |
          pip install pytest  # Install pytest for running tests

      - name: Run script
        run: python Hello.py  # Run the Hello.py script

      - name: Run tests
        run: pytest test_Hello.py  # Run tests in test_Hello.py

