# .github/workflows/ci.yml
name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'  # Use the Python version you need

      - name: Run script
        run: python Hello.py  # Replace `your_script.py` with your Python file

      # Uncomment the lines below if you have tests to run
      # - name: Run tests
      #   run: python -m unittest discover  # For a simple unittest setup

